### ISSUE TITLE
Forbidden for part of dataset

### ISSUE THREAD

**Issue by simonjisu** [allenai/sherlock#3]
# Issue

Hi! Thank you for your great work. I am trying to explore your dataset(from Korea), 
However I cannot reach some of data url, especially in `cs.standford.edu` domain.
I tried add headers in python request module:

```python
import requests

session = requests.Session()
url = 'https://cs.stanford.edu/people/rak248/VG_100K/2364638.jpg'
response = session.get(url, headers={'User-Agent': 'Mozilla/5.0'})
response.status_code
# returns 403
```

How can I fix this issue? Let me attach the image when I try to access following link in the Chorme:
- https://cs.stanford.edu/people/rak248/VG_100K/2364638.jpg

![image](https://user-images.githubusercontent.com/28801714/194903417-f389f638-41a1-456d-ad62-694131f26660.png)

**Comment by jmhessel** [comment]
Hi @simonjisu 

thanks for your interest in our work! I would recommend downloading the visual genome images locally rather than accessing them via the URLs. The images are available here: https://visualgenome.org/api/v0/api_home.html

Jack

**Comment by jmhessel** [comment]
(I will close for now because I think this addresses your question; feel free to re-open if I can be helpful further)

**Comment by simonjisu** [comment]
Thank you very much!😄
