### ISSUE TITLE
VisualGenome Images Download link does not work.

### ISSUE THREAD

**Issue by RaisnnowLawrence** [allenai/sherlock#4]
Images Download link “VisualGenome Images Download” does not work now.
Is there another way to download this dataset?

**Comment by jmhessel** [comment]
Hi @RaisnnowLawrence ! Thanks for your interest in our work. I also noticed the visual genome site www.visualgenome.org is currently down, so this issue extends beyond Sherlock. I am hopeful it can be resolved soon, I plan to ping the authors about it.

**Comment by RaisnnowLawrence** [comment]
> Hi @RaisnnowLawrence ! Thanks for your interest in our work. I also noticed the visual genome site [www.visualgenome.org](http://www.visualgenome.org) is currently down, so this issue extends beyond Sherlock. I am hopeful it can be resolved soon, I plan to ping the authors about it.

I understand the situation, thank you!

**Comment by jmhessel** [comment]
Hi @RaisnnowLawrence --- here's a partial answer. https://twitter.com/jmhessel/status/1654205341251538947

I might host the images soon as well if I can dig them up, I'll let you know.

**Comment by jmhessel** [comment]
new site : https://homes.cs.washington.edu/~ranjay/visualgenome/index.html
